version: '3.9'
services:
  app:
    image: phinixhq/electrumx-exporter
    restart: unless-stopped
    environment: 
      REFRESH_INTERVAL_MILLISECONDS: "30000"
      ELECTRUMX_HOST:
      ELECTRUMX_PORT:
      COIN:
    network_mode: "host"
